# Trigger the pipeline on each push to the main branch
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Reference the variable group with AWS credentials
  - group: 'AWS_Credentials'
    INSTANCE_IP: '63.33.65.6'
  PRIVATE_KEY_PATH: 'kaungkey0'

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Set up Docker
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'kaung/flaskapp'
    dockerfile: 'flask_dockerfile'
    tags: |
      $(Build.BuildId)

# Step 3: Deploy to AWS EC2
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ssh -i kaungkey0 -o "StrictHostKeyChecking=no" ubuntu@$(INSTANCE_IP) << 'EOF'
        docker pull kaung/flaskapp:$(Build.BuildId)
        docker stop flask_app_container || true
        docker rm flask_app_container || true
        docker run -d -p 80:5000 --name flask_app_container kaung/flaskapp:$(Build.BuildId)
      EOF
